spring:
  application.name: gateway # This is service id
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: accept
        uri: lb://accept-ticket-service:8080
        predicates:
#        - Host=localhost
        - Path=/v2/accept/**
        filters:
         - RewritePath=/v2/(?<segment>.*), /$\{segment}

      - id: payout
        uri: http://payout:8080
        predicates:
        - Path=/payout/**

      - id: scheduler
        uri: http://scheduler:8080
        predicates:
          - Path=/scheduler/**

      - id: static
        uri: lb://accept-ticket-static-service:8080
        predicates:
#        - Host=static
        - Path=/v1/accept/**
        filters:
        - RewritePath=/v1/(?<segment>.*), /$\{segment}

      - id: eureka
        uri: http://localhost:8761/
        predicates:
        - Path=/eureka/**

server:
  port: 9000

